CREATE TABLE IF NOT EXISTS TB_PESSOA_FISICA (
    CPF VARCHAR(100) NOT NULL,
    NOME VARCHAR(100),
    PRIMARY KEY (CPF)
);

CREATE TABLE TB_PESSOA_JURIDICA (
    CNPJ VARCHAR(100) NOT NULL,
    NOME_FANTASIA VARCHAR(100),
    RAZAO_SOCIAL VARCHAR(100),
    PRIMARY KEY (CNPJ)
);
